sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t lmachraf/frontend

script:
  - docker run -e CI=true lmachraf/frontend npm run test -- --coverage